%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Step 2: Forecasting Comparison
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This script runs the main forecasting comparison for ozone concentration
% surfaces. It assumes that Step 1 has already been executed and that the
% files Data/SeasonAdjData.mat and Data/FTSs.mat are available.
%
% The script compares the following forecasting methods:
%
%   1. MF       - mean forecast
%   2. NF       - naive forecast
%   3. FAR      - functional autoregressive forecast
%   4. PCA VAR  - static FPCA scores + VARX
%   5. PCA KNN  - static FPCA scores + KNN
%   6. DS VAR   - dynamic scores + VARX
%   7. DS KNN   - dynamic scores + KNN
%   8. MP VAR   - multivariate perspective from station/grid values + VARX
%   9. MP KNN   - multivariate perspective from station/grid values + KNN
%  10. DS RF    - dynamic scores + random forest
%
% Practitioner settings are collected at the beginning of the file. In most
% applications, these are the only values that should be changed.
%
% Output:
%   All outputs are saved directly in the folder "Outputs". If this folder
%   does not exist, it is created automatically.
%
% Important notes:
%   - The script is written with a standard FOR loop for easier replication.
%     The main loop can be changed to PARFOR if the Parallel
%     Computing Toolbox is available.
%   - The random forest forecast requires the Statistics and Machine Learning
%     Toolbox.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all;
clc;
close all;

%% Add libraries
addpath AddFunc
addpath Data

%% Output folder

outFolder = fullfile(pwd,'Outputs');
if ~exist(outFolder,'dir')
    mkdir(outFolder);
end

%% Practitioner settings
% Change these values if you want to run a different specification.

H       = 165;    % number of final observations used for forecast evaluation
h       = 7;      % forecast horizon; h = 1 is the main paper specification
K_max   = 10;     % maximum number of estimated scores/components
KNN_max = 50;     % maximum number of neighbours considered in KNN calibration
q_dyn   = 2;      % number of lags in the cumulative autocovariance operator

% Number of score components and lags.
% The first entry corresponds to ozone.
% The remaining entries correspond to: Sun, Precip, Temp, Wind.
%
% Example:
%   [4 1 1 1 1] means:
%       ozone uses 4 scores;
%       each covariate uses 1 score.

Static_L_set = [8 1 1 1 1];   % static FPCA score dimensions
Static_m_set = [2 1 1 1 1];   % static FPCA lag orders

Dyn_L_set    = [4 1 1 1 1];   % dynamic-score dimensions
Dyn_m_set    = [2 1 1 1 1];   % dynamic-score lag orders

% Surface reconstruction / plotting settings

Threshold = 0.75;             % threshold used by CleanTriangulation

% Figure export settings

figResolution = 300;

%% Step 1: Read data
% Loads seasonally adjusted data at observed locations and surface time
% series generated by Step 1.

load('Data\SeasonAdjData');   % seasonally adjusted data on observed locations
load('Data\FTSs');            % functional surface time series from Step 1

ConstrReg = csvread('Data/GeoConstraints/DE_Constraints.csv');

%% Data checks
[~,T] = size(OzoneS);

if H >= T
    error('H must be smaller than the total sample size T.');
end

if h < 1
    error('Forecast horizon h must be a positive integer.');
end

if h > H
    error('Forecast horizon h cannot exceed H.');
end

if K_max < max([Static_L_set(1), Dyn_L_set(1)])
    error('K_max must be at least as large as the maximum number of ozone scores.');
end

if KNN_max < 1
    error('KNN_max must be positive.');
end

%% Project coordinates
% Projection: Gauss-Krüger Zone 3, EPSG:31467.
% This requires the Mapping Toolbox.

wgs84           = geocrs(4326);
proj            = projcrs(31467);

[LonOz,  LatOz] = projfwd(proj, LatOz, LonOz);

[x, y]          = projfwd(proj, ConstrReg(:,1), ConstrReg(:,2));
ConstrReg       = [y,x];

[XPrecip,YPrecip] = projfwd(proj, YPrecip, XPrecip);
[XWind,  YWind]   = projfwd(proj, YWind, XWind);
[XSun,   YSun]    = projfwd(proj, YSun, XSun);
[XTemp,  YTemp]   = projfwd(proj, YTemp, XTemp);

%% Step 2: Initial values for forecast comparison

N_Fors   = H+1-h;
FEMBasOz = OzoneBasis;

% Forecast error surfaces.
% Each column corresponds to one forecast origin.
% MSEs are computed after the loop by squaring and averaging these errors.

MSurf_MP      = zeros(size(OzoneS,1),N_Fors);
MSurf_NP      = zeros(size(OzoneS,1),N_Fors);
MSurf_FAR1    = zeros(size(OzoneS,1),N_Fors);

MSurf_PCA_VAR = zeros(size(OzoneS,1),N_Fors);
MSurf_PCA_KNN = zeros(size(OzoneS,1),N_Fors);

MSurf_DS_VAR  = zeros(size(OzoneS,1),N_Fors);
MSurf_DS_KNN  = zeros(size(OzoneS,1),N_Fors);

MSurf_MP_VAR  = zeros(size(OzoneS,1),N_Fors);
MSurf_MP_KNN  = zeros(size(OzoneS,1),N_Fors);

MSurf_RF      = zeros(size(OzoneS,1),N_Fors);

% Selected KNN neighbours, saved for inspection.

KNNs  = zeros(N_Fors,1);   % PCA KNN
KNNDS = zeros(N_Fors,1);   % DS KNN
KNNGs = zeros(N_Fors,1);   % MP KNN

%% Step 3: Forecasting with different methods
% For each forecast origin, the estimation sample is expanded by one day.
% The forecast is then evaluated against the true surface at t+h.

tic

for i = 1:N_Fors

    %% Part of the data used for estimation

    nobs_i  = T-H+i-1;
    TrueFD  = fd(OzoneCoef(:,nobs_i+h),OzoneBasis);
    TrueVal = eval_FEM_fd(LonOz,LatOz,TrueFD);
    % TrueVal = OzoneS(:,nobs_i+h);

    %% Static and dynamic scores

    dynstrOz_i = DynamScoresSurf({OzoneCoef(:,1:nobs_i),OzoneBasis}, ...
                                  K_max, 1, q_dyn);

    pcastrOz_i = pca3D({OzoneCoef(:,1:nobs_i),OzoneBasis}, K_max, 1);

    pcastrS_i  = pca3D({SunCoef(:,1:nobs_i),SunBasis}, K_max, 1);
    pcastrP_i  = pca3D({PrecipCoef(:,1:nobs_i),PrecipBasis}, K_max, 1);
    pcastrT_i  = pca3D({TempCoef(:,1:nobs_i),TempBasis}, K_max, 1);
    pcastrW_i  = pca3D({WindCoef(:,1:nobs_i),WindBasis}, K_max, 1);

    PCA_addreg = {pcastrS_i,pcastrP_i,pcastrT_i,pcastrW_i};

    %% Method 1: Mean forecast

    MSurf_MP(:,i) = TrueVal - mean(OzoneS(:,1:nobs_i),2);

    %% Method 2: Naive forecast

    MSurf_NP(:,i) = TrueVal - OzoneS(:,nobs_i);

    %% Method 3: Functional autoregressive forecast

    FuncPredCoeff = SFAR1(pcastrOz_i,Static_L_set(1),h);
    FuncPred      = fd(FuncPredCoeff,FEMBasOz);
    FPointEval    = eval_FEM_fd(LonOz,LatOz,FuncPred);

    MSurf_FAR1(:,i) = TrueVal - FPointEval;

    %% Method 4: PCA VAR

    FuncPredCoeff = FFM_VARX(pcastrOz_i,PCA_addreg, ...
                              Static_L_set,Static_m_set,h);
    FuncPred      = fd(FuncPredCoeff,FEMBasOz);
    FPointEval    = eval_FEM_fd(LonOz,LatOz,FuncPred);

    MSurf_PCA_VAR(:,i) = TrueVal - FPointEval;

    %% Method 5: PCA KNN
    K_NNv       = zeros(KNN_max,1);
    pcastrKNN_i = pca3D({OzoneCoef(:,1:nobs_i-h),OzoneBasis}, K_max, 1);

    for knn = 1:KNN_max

        FuncPredCoeff = FFM_KNN(pcastrKNN_i, ...
                                Static_L_set(1),Static_m_set(1),knn,h);
        FuncPred      = fd(FuncPredCoeff,FEMBasOz);
        FPointEval    = eval_FEM_fd(LonOz,LatOz,FuncPred);

        K_NNv(knn,1)  = mean((OzoneS(:,nobs_i)-FPointEval).^2);

    end

    [~,K_min] = min(K_NNv);
    KNNs(i,1) = K_min;

    FuncPredCoeff = FFM_KNN(pcastrOz_i, ...
                            Static_L_set(1),Static_m_set(1),K_min,h);
    FuncPred      = fd(FuncPredCoeff,FEMBasOz);
    FPointEval    = eval_FEM_fd(LonOz,LatOz,FuncPred);

    MSurf_PCA_KNN(:,i) = TrueVal - FPointEval;

    %% Method 6: DS VAR

    FuncPredCoeff = FFM_VARX(dynstrOz_i,PCA_addreg, ...
                              Dyn_L_set,Dyn_m_set,h);
    FuncPred      = fd(FuncPredCoeff,FEMBasOz);
    FPointEval    = eval_FEM_fd(LonOz,LatOz,FuncPred);
    MSurf_DS_VAR(:,i) = TrueVal - FPointEval;

    %% Method 7: DS KNN
    K_NNv      = zeros(KNN_max,1);
    dynstrKNN_i = DynamScoresSurf({OzoneCoef(:,1:nobs_i-h),OzoneBasis}, K_max, 1, q_dyn);

    for knn = 1:KNN_max
        FuncPredCoeff = FFM_KNN(dynstrKNN_i,Dyn_L_set(1),Dyn_m_set(1),knn,h);
        FuncPred      = fd(FuncPredCoeff,FEMBasOz);
        FPointEval    = eval_FEM_fd(LonOz,LatOz,FuncPred);
        K_NNv(knn,1)  = mean((OzoneS(:,nobs_i)-FPointEval).^2);
    end

    [~,K_min]     = min(K_NNv);
    KNNDS(i,1)    = K_min;
    FuncPredCoeff = FFM_KNN(dynstrOz_i,Dyn_L_set(1),Dyn_m_set(1),K_min,h);
    FuncPred      = fd(FuncPredCoeff,FEMBasOz);
    FPointEval    = eval_FEM_fd(LonOz,LatOz,FuncPred);
    MSurf_DS_KNN(:,i) = TrueVal - FPointEval;

    %% Method 8: MP VAR
    % Multivariate perspective: score vectors are estimated directly from
    % the station/grid data rather than from reconstructed surfaces.

    FPredGrid = DFFM_VARX_GRID(OzoneS(:,1:nobs_i),WindS(:,1:nobs_i),SunS(:,1:nobs_i), ...
                               PrecipS(:,1:nobs_i),TempS(:,1:nobs_i),Static_L_set,Static_m_set,h);
    MSurf_MP_VAR(:,i) = TrueVal - FPredGrid;

    %% Method 9: MP KNN
    % KNN applied to score vectors estimated directly from station/grid data.

    K_NNv    = zeros(KNN_max,1);
    pcastr_i = FactorDecompFTSGrid(OzoneS(:,1:nobs_i-h), K_max, 1);

    for knn = 1:KNN_max

        FPredGrid    = DFFM_KNN_GRID(pcastr_i, ...
                                     Static_L_set(1),Static_m_set(1),knn);
        K_NNv(knn,1) = mean((OzoneS(:,nobs_i)-FPredGrid).^2);

    end

    [~,K_min]  = min(K_NNv);
    KNNGs(i,1) = K_min;

    pcastr_i  = FactorDecompFTSGrid(OzoneS(:,1:nobs_i), K_max, 1);
    FPredGrid = DFFM_KNN_GRID(pcastr_i, ...
                              Static_L_set(1),Static_m_set(1),K_min);

    MSurf_MP_KNN(:,i) = TrueVal - FPredGrid;

    %% Method 10: DS random forest

    FuncPredCoeff = FRandomForest(dynstrOz_i,Dyn_L_set(1),h);
    FuncPred      = fd(FuncPredCoeff,FEMBasOz);
    FPointEval    = eval_FEM_fd(LonOz,LatOz,FuncPred);

    MSurf_RF(:,i) = TrueVal - FPointEval;

    %% Progress update

    fprintf('Forecast %d/%d completed.\n', i, N_Fors);

end

runTime = toc;

%% Step 4: Forecast evaluation

Models = {'MF','NF','FAR','PCA VAR','PCA KNN','DS VAR','DS KNN','MP VAR','MP KNN','DS RF'};

MSurf = {MSurf_MP, MSurf_NP, MSurf_FAR1,MSurf_PCA_VAR, MSurf_PCA_KNN,MSurf_DS_VAR, MSurf_DS_KNN, ...
         MSurf_MP_VAR, MSurf_MP_KNN,MSurf_RF};

MSE_MP      = mean(MSurf_MP.^2,1)';
MSE_NP      = mean(MSurf_NP.^2,1)';
MSE_FAR1    = mean(MSurf_FAR1.^2,1)';
MSE_PCA_VAR = mean(MSurf_PCA_VAR.^2,1)';
MSE_PCA_KNN = mean(MSurf_PCA_KNN.^2,1)';
MSE_DS_VAR  = mean(MSurf_DS_VAR.^2,1)';
MSE_DS_KNN  = mean(MSurf_DS_KNN.^2,1)';
MSE_MP_VAR  = mean(MSurf_MP_VAR.^2,1)';
MSE_MP_KNN  = mean(MSurf_MP_KNN.^2,1)';
MSE_RF      = mean(MSurf_RF.^2,1)';

MSE_All = [MSE_MP, MSE_NP, MSE_FAR1,MSE_PCA_VAR, MSE_PCA_KNN,MSE_DS_VAR, MSE_DS_KNN, ...
           MSE_MP_VAR, MSE_MP_KNN,MSE_RF];

MeanMSE = mean(MSE_All);

MeanMSE_Table = array2table(MeanMSE,'VariableNames', matlab.lang.makeValidName(Models));

disp(MeanMSE_Table)

%% Save numerical results

dateStr = datestr(now,'yyyymmdd_HHMMSS');

Settings.H            = H;
Settings.h            = h;
Settings.K_max        = K_max;
Settings.KNN_max      = KNN_max;
Settings.q_dyn        = q_dyn;
Settings.Static_L_set = Static_L_set;
Settings.Static_m_set = Static_m_set;
Settings.Dyn_L_set    = Dyn_L_set;
Settings.Dyn_m_set    = Dyn_m_set;
Settings.Threshold    = Threshold;
Settings.runTime      = runTime;

save(fullfile(outFolder, ...
    ['ForecastComparison_h',num2str(h),'_',dateStr,'.mat']), ...
    'Settings', 'Models', 'MSurf', 'MSE_All', 'MeanMSE', ...
    'MSurf_MP', 'MSurf_NP', 'MSurf_FAR1', ...
    'MSurf_PCA_VAR', 'MSurf_PCA_KNN', ...
    'MSurf_DS_VAR', 'MSurf_DS_KNN', ...
    'MSurf_MP_VAR', 'MSurf_MP_KNN', 'MSurf_RF', ...
    'MSE_MP', 'MSE_NP', 'MSE_FAR1', ...
    'MSE_PCA_VAR', 'MSE_PCA_KNN', ...
    'MSE_DS_VAR', 'MSE_DS_KNN', ...
    'MSE_MP_VAR', 'MSE_MP_KNN', 'MSE_RF', ...
    'KNNs', 'KNNDS', 'KNNGs');

writetable(MeanMSE_Table, ...
    fullfile(outFolder,['ForecastComparison_MeanMSE_h',num2str(h),'.csv']));

MSE_Table = array2table(MSE_All, ...
    'VariableNames', matlab.lang.makeValidName(Models));

writetable(MSE_Table, ...
    fullfile(outFolder,['ForecastComparison_MSE_byOrigin_h',num2str(h),'.csv']));

%% Step 5: Boxplot figure

figBox = figure(1);
FS     = 14;
canvas = [100, 100, 1000, 350];

set(figBox, 'Position', canvas, 'PaperPositionMode', 'auto');

bh = boxplot(MSE_All, 'Labels', Models, 'whisker', 2);
set(bh(7,:), 'Visible', 'off');

ylabel('MSE', 'FontSize', FS);
boxplotYLim = [0 500];
xtickangle(30)

if ~isempty(boxplotYLim)
    ylim(boxplotYLim);
end

grid on

exportgraphics(figBox, ...
    fullfile(outFolder,['BoxplotsHorizon',num2str(h),'.pdf']), ...
    'BackgroundColor', 'none', ...
    'Resolution', figResolution, ...
    'ContentType', 'vector');

exportgraphics(figBox, ...
    fullfile(outFolder,['BoxplotsHorizon',num2str(h),'.png']), ...
    'BackgroundColor', 'white', ...
    'Resolution', figResolution);

savefig(figBox, ...
    fullfile(outFolder,['BoxplotsHorizon',num2str(h),'.fig']));

%% Step 6: MSE surface figures

DTOzone   = delaunayTriangulation([LonOz,LatOz]);
CleanDTOz = CleanTriangulation(DTOzone,[ConstrReg(:,2),ConstrReg(:,1)],Threshold);

Region     = [ConstrReg(:,2),ConstrReg(:,1)];
RegionBord = polyshape(Region);

MSESurf = cellfun(@(M) mean(M.^2,2), MSurf, 'UniformOutput', false);

all_mse   = cell2mat(MSESurf');
bottomMSE = min(all_mse, [], 'all');
topMSE    = max(all_mse, [], 'all');

figMSE = figure(2);
figMSE.Position = [100, 100, 1500, 650];

for mm = 1:length(Models)

    subplot(2,5,mm)

    Season = Grid2Func(MSESurf{mm}, DTOzone, CleanDTOz);

    hold on
        plot(RegionBord, 'FaceColor', 'none');
        plot(Season, [], [], [], 100);
    hold off

    axis equal tight;
    colormap(jet);
    clim([bottomMSE topMSE]);
    colorbar;
    view(2);

    title(Models{mm});
    xlabel('Easting');
    ylabel('Northing');

end

exportgraphics(figMSE, ...
    fullfile(outFolder,['MSESurfacesHorizon',num2str(h),'.pdf']), ...
    'BackgroundColor', 'none', ...
    'Resolution', figResolution, ...
    'ContentType', 'vector');

exportgraphics(figMSE, ...
    fullfile(outFolder,['MSESurfacesHorizon',num2str(h),'.png']), ...
    'BackgroundColor', 'white', ...
    'Resolution', figResolution);

savefig(figMSE, ...
    fullfile(outFolder,['MSESurfacesHorizon',num2str(h),'.fig']));

%% Save spatial MSE surfaces separately

MSESurf_Table = table();

for mm = 1:length(Models)

    varName = matlab.lang.makeValidName(Models{mm});
    MSESurf_Table.(varName) = MSESurf{mm};

end

writetable(MSESurf_Table, ...
    fullfile(outFolder,['ForecastComparison_MSE_surfaces_h',num2str(h),'.csv']));

fprintf('\nForecasting comparison completed.\n');
fprintf('All outputs saved in: %s\n', outFolder);
